#!/bin/bash
pcount=$#
if((pcount==0)); then
  echo no args;
  exit;
fi
p1=$1
fname=`basename $p1`
echo fname=$fname

pdir=`cd -P $(dirname $p1); pwd`
echo pdir=$pdir

user=`whoami`

for host in node001 node002 node003
do
	echo ---------------$host----------
	rsync -rvl $pdir/$fname $user@$host:$pdir
done

