insert overwrite table dwd_display_log select mid_id,
    user_id,
    version_code,
    version_name,
    lang,
    source,
    os,
    area,
    model,
    brand,
    sdk_version,
    gmail,
    height_width,
    app_time,
    network,
    lng,
    lat,
    get_json_object(event_json,'$.kv.action') action,
    get_json_object(event_json,'$.kv.newsid') newsid,
    get_json_object(event_json,'$.kv.place') place,
    get_json_object(event_json,'$.kv.extend1') extend1,
    get_json_object(event_json,'$.kv.category') category,
    server_time,
    dt
    from dwd_base_event_log where dt='2022-10-15' and event_name='display';


insert overwrite table dwd_newsdetail_log select mid_id,
    user_id,
    version_code,
    version_name,
    lang,
    source,
    os,
    area,
    model,
    brand,
    sdk_version,
    gmail,
    height_width,
    app_time,
    network,
    lng,
    lat,
    get_json_object(event_json,'$.kv.entry') entry,
    get_json_object(event_json,'$.kv.action') action,
    get_json_object(event_json,'$.kv.newsId') newsId,
    get_json_object(event_json,'$.kv.showStyle') showStyle,
    get_json_object(event_json,'$.kv.newsStayTime') newsStayTime,
    get_json_object(event_json,'$.kv.loadingTime') loadingTime,
    get_json_object(event_json,'$.kv.type1') type1,
    get_json_object(event_json,'$.kv.category') category,
    server_time,
    dt
from dwd_base_event_log where dt='2022-10-15' and event_name='newsdetail';


insert overwrite table dwd_loading_log select mid_id,
    user_id,
    version_code,
    version_name,
    lang,
    source,
    os,
    area,
    model,
    brand,
    sdk_version,
    gmail,
    height_width,
    app_time,
    network,
    lng,
    lat,
    get_json_object(event_json,'$.kv.action') action,
    get_json_object(event_json,'$.kv.loadingTime') loadingTime,
    get_json_object(event_json,'$.kv.loadingWay') loadingWay,
    get_json_object(event_json,'$.kv.extend1') extend1,
    get_json_object(event_json,'$.kv.extend2') extend2,
    get_json_object(event_json,'$.kv.type') type,
    get_json_object(event_json,'$.kv.type1') type1,
    server_time,
    dt
from dwd_base_event_log where dt='2022-10-15' and event_name='loading';

insert overwrite table dwd_ad_log select mid_id,
    user_id,
    version_code,
    version_name,
    lang,
    source,
    os,
    area,
    model,
    brand,
    sdk_version,
    gmail,
    height_width,
    app_time,
    network,
    lng,
    lat,
    get_json_object(event_json,'$.kv.entry') entry,
    get_json_object(event_json,'$.kv.action') action,
    get_json_object(event_json,'$.kv.content') content,
    get_json_object(event_json,'$.kv.detail') detail,
    get_json_object(event_json,'$.kv.source') source,
    get_json_object(event_json,'$.kv.behavior') behavior,
    get_json_object(event_json,'$.kv.newsType') newsType,
    get_json_object(event_json,'$.kv.showStyle') showStyle,
    server_time,
    dt
from dwd_base_event_log where dt='2022-10-15' and event_name='dwd_ad_log';

insert overwrite table dwd_notification_log select mid_id,
    user_id,
    version_code,
    version_name,
    lang,
    source,
    os,
    area,
    model,
    brand,
    sdk_version,
    gmail,
    height_width,
    app_time,
    network,
    lng,
    lat,
    get_json_object(event_json,'$.kv.action') action,
    get_json_object(event_json,'$.kv.type') type,
    get_json_object(event_json,'$.kv.apTime') apTime,
    get_json_object(event_json,'$.kv.content') content,
    server_time,
    dt
from dwd_base_event_log where dt='2022-10-15' and event_name='notification';


insert overwrite table dwd_active_foreground_log select mid_id,
    user_id,
    version_code,
    version_name,
    lang,
    source,
    os,
    area,
    model,
    brand,
    sdk_version,
    gmail,
    height_width,
    app_time,
    network,
    lng,
    lat,
    get_json_object(event_json,'$.kv.pushId') pushId,
    get_json_object(event_json,'$.kv.access') access,
    server_time,
    dt
from dwd_base_event_log where dt='2022-10-15' and event_name='active_foreground';

insert overwrite table dwd_active_background_log select mid_id,
    user_id,
    version_code,
    version_name,
    lang,
    source,
    os,
    area,
    model,
    brand,
    sdk_version,
    gmail,
    height_width,
    app_time,
    network,
    lng,
    lat,
    get_json_object(event_json,'$.kv.activeSource') activeSource,
    server_time,
    dt
from dwd_base_event_log where dt='2022-10-15' and event_name='active_background';

insert overwrite table dwd_comment_log select mid_id,
    user_id,
    version_code,
    version_name,
    lang,
    source,
    os,
    area,
    model,
    brand,
    sdk_version,
    gmail,
    height_width,
    app_time,
    network,
    lng,
    lat,
    get_json_object(event_json,'$.kv.commentId') commentId,
    get_json_object(event_json,'$.kv.userId') userId,
    get_json_object(event_json,'$.kv.pCommentId') pCommentId,
    get_json_object(event_json,'$.kv.content') content,
    get_json_object(event_json,'$.kv.addTime') addTime,
    get_json_object(event_json,'$.kv.otherId') otherId,
    get_json_object(event_json,'$.kv.praiseCount') praiseCount,
    get_json_object(event_json,'$.kv.replyCount') replyCount,
    server_time,
    dt
from dwd_base_event_log where dt='2022-10-15' and event_name='comment';


insert overwrite table dwd_favorites_log select mid_id,
    user_id,
    version_code,
    version_name,
    lang,
    source,
    os,
    area,
    model,
    brand,
    sdk_version,
    gmail,
    height_width,
    app_time,
    network,
    lng,
    lat,
    get_json_object(event_json,'$.kv.id') id,
    get_json_object(event_json,'$.kv.courseId') courseId,
    get_json_object(event_json,'$.kv.userId') userId,
    get_json_object(event_json,'$.kv.addTime') addTime,
    server_time,
    dt
from dwd_base_event_log where dt='2022-10-15' and event_name='favorites';


insert overwrite table dwd_praise_log select mid_id,
    user_id,
    version_code,
    version_name,
    lang,
    source,
    os,
    area,
    model,
    brand,
    sdk_version,
    gmail,
    height_width,
    app_time,
    network,
    lng,
    lat,
    get_json_object(event_json,'$.kv.id') id,
    get_json_object(event_json,'$.kv.userId') userId,
    get_json_object(event_json,'$.kv.targetId') targetId,
    get_json_object(event_json,'$.kv.type') type,
    get_json_object(event_json,'$.kv.addTime') addTime,
    server_time,
    dt
from dwd_base_event_log where dt='2022-10-15' and event_name='praise';


insert overwrite table dwd_start_log select mid_id,
    user_id,
    version_code,
    version_name,
    lang,
    source,
    os,
    area,
    model,
    brand,
    sdk_version,
    gmail,
    height_width,
    app_time,
    network,
    lng,
    lat,
    get_json_object(event_json,'$.kv.entry') entry,
    get_json_object(event_json,'$.kv.openAdType') openAdType,
    get_json_object(event_json,'$.kv.action') action,
    get_json_object(event_json,'$.kv.loadingTime') loadingTime,
    get_json_object(event_json,'$.kv.detail') detail,
    get_json_object(event_json,'$.kv.extend1') extend1,
    server_time,
    dt
from dwd_base_start_log where dt='2022-10-15' and event_name='start';


insert overwrite table dwd_error_log select mid_id,
    user_id,
    version_code,
    version_name,
    lang,
    source,
    os,
    area,
    model,
    brand,
    sdk_version,
    gmail,
    height_width,
    app_time,
    network,
    lng,
    lat,
    get_json_object(event_json,'$.kv.errorBrief') errorBrief,
    get_json_object(event_json,'$.kv.errorDetail') errorDetail,
    server_time,
    dt
from dwd_base_event_log where dt='2022-10-15' and event_name='error';